server:
  port: 8899
spring:
  application:
    name: demo-provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #配置Swagger相关信息
  instance:
    prefer-ip-address: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    # ${server.port}为该服务的端口号
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
dubbo:
  application:
    name: demo-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    basePackages: cn.springcloud.book